
version: 2

models:

  - name: Dim_Customer
    description: "Customer Dimention based in customer and nation"
    database: 'analytics'
    schema: 'snapshots'

  - name: Fact_Orders
    description: "Orders Fact table using orders and calculated dim_customer"
    database: 'analytics'
    schema: 'snapshots'
